# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import account_pb2 as account__pb2


class AccountStub(object):
    """define a service
    Here, we demonstrate two types of rpc connection:
    - GetAccount demonstrates a unary connection (similar to a GET request in REST)
    - StreamIndustryIds demonstrates a client-side streaming connection (responses are streamed (server yields results, client iterate over iterator))
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetAccount = channel.unary_unary(
                '/account.Account/GetAccount',
                request_serializer=account__pb2.GetAccountRequest.SerializeToString,
                response_deserializer=account__pb2.GetAccountResponse.FromString,
                )
        self.StreamIndustryIds = channel.unary_stream(
                '/account.Account/StreamIndustryIds',
                request_serializer=account__pb2.StreamIndustryIdsRequest.SerializeToString,
                response_deserializer=account__pb2.StreamIndustryIdsResponse.FromString,
                )


class AccountServicer(object):
    """define a service
    Here, we demonstrate two types of rpc connection:
    - GetAccount demonstrates a unary connection (similar to a GET request in REST)
    - StreamIndustryIds demonstrates a client-side streaming connection (responses are streamed (server yields results, client iterate over iterator))
    """

    def GetAccount(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamIndustryIds(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AccountServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetAccount': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAccount,
                    request_deserializer=account__pb2.GetAccountRequest.FromString,
                    response_serializer=account__pb2.GetAccountResponse.SerializeToString,
            ),
            'StreamIndustryIds': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamIndustryIds,
                    request_deserializer=account__pb2.StreamIndustryIdsRequest.FromString,
                    response_serializer=account__pb2.StreamIndustryIdsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'account.Account', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Account(object):
    """define a service
    Here, we demonstrate two types of rpc connection:
    - GetAccount demonstrates a unary connection (similar to a GET request in REST)
    - StreamIndustryIds demonstrates a client-side streaming connection (responses are streamed (server yields results, client iterate over iterator))
    """

    @staticmethod
    def GetAccount(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/account.Account/GetAccount',
            account__pb2.GetAccountRequest.SerializeToString,
            account__pb2.GetAccountResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def StreamIndustryIds(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/account.Account/StreamIndustryIds',
            account__pb2.StreamIndustryIdsRequest.SerializeToString,
            account__pb2.StreamIndustryIdsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
